#!/usr/bin/ansible-playbook
- name: Intro ansible playbooks
  hosts: all
  remote_user: ec2-user
  become: 'yes'
  become_user: root

  tasks:
    - name: Checking connection via Ping
      ping:
    - name: Uninstall apacher WebServer
      yum:
        name: httpd
        state: absent